docker-compose.yml
this builds catalina with 200G of disk space
=> add example docker-compose

Dockerfile
=> Remove yay dependancy

Dockerfile
This PR regroup some of RUN commands into one in order to reduce the number of layers of the Dockerfile.
=> Reduce number of layers in Dockerfile

Dockerfile, README.md
I have changed a few things,
1. Updated macOS version 10.15.5 -> 10.15.6
2. Enabled screen sharing port forwarding
3. Removed the need to remove 1gb from the partition.
=> Improvments

README.md
Firstly, amazing job with this project - I couldn't believe how simple it was to get started and how seamlessly it works.
I had to reinstall a few times to get the capacity right to fit Xcode. Just wanted to save others the trouble by noting the min. needed disk size for Xcode. In my case 50gb was too little, so the exact right amount lies between 50-60gb.
=> Made instructions more clear for those needing Xcode

Dockerfile
Less image layer, more maintainable and readable!
=> Simplify .ssh directory setup process in Dockerfile

Dockerfile, README.md
Add HUGE internet speed increases.
Gigabit speeds++ inside the guest.
Simply use on any image:
`-e NETWORKING=vmxnet3`
=> Add -e NETWORKING=e1000-82545em || -e NETWORKING=vmxnet3 as runtime arguments.

CHANGELOG.md, Dockerfile, Dockerfile.auto, README.md
Add `NOPICKER=false` in `:latest`.
Add `NOPICKER=true` in `:auto`.
Add networking speed docs: 
`-e NETWORKING=e1000-82545em`
`-e NETWORKING=vmxnet3`
=> NOPICKER environment variable for all images.

Dockerfile
Add bigsur BaseSystem.img support. Use `--build-arg VERSION=11` or higher.
Downloads latest version currently.
If you want to select verisons, submit a PR to @acidanthera's great project to get the version option https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macrecovery/macrecovery.py
=> Add bigsur BaseSystem.img support. Use `--build-arg VERSION=11` 

CHANGELOG.md, CREDITS.md, Dockerfile
Add `ADDITIONAL_PORTS`
For example, `-e ADDITIONAL_PORTS='hostfwd=tcp::10023-:80,'`
And add `-p 10023:10023` or similar to the docker run command
```
-e ADDITIONAL_PORTS='hostfwd=tcp::10023-:80,' \
-p 10023:10023 \
```
=> Add ADDITIONAL_PORTS, -e ADDITIONAL_PORTS='hostfwd=tcp::10023-:80,'

custom/generate-specific-bootdisk.sh, custom/generate-unique-machine-values.sh
Update custom from https://github.com/sickcodes/osx-serial-generator.git
Mentioned in https://github.com/sickcodes/Docker-OSX/issues/244#issuecomment-820153982
=> Update custom from https://github.com/sickcodes/osx-serial-generator.git

CREDITS.md, Dockerfile, Dockerfile.auto, Dockerfile.naked
Forgot to add file downgrade to all images.
=> Downgrade file to 5.39 due to libguestfs bug. All Dockerfiles though.

README.md
There was the same line twice. Removed one.
=> Fixed Type

Dockerfile, Dockerfile.auto, Dockerfile.naked
Fixes https://github.com/sickcodes/Docker-OSX/issues/323
Fixes https://github.com/sickcodes/Docker-OSX/issues/322
=> Remove glibc patches, introduce libguestfs test

CHANGELOG.md, Dockerfile.monterey, README.md, tests/test.sh
=> Add `sickcodes/docker-osx:monterey`!

README.md
build takes --build-arg and not -e, as I understand
=> fix Big Sur build example

README.md
Adds the notes to the README.md under the "Mounting a Folder" section.
=> Notes for mounting an NFS folder from a linux host

Dockerfile, Dockerfile.auto, Dockerfile.naked, Dockerfile.naked-auto
Lower the container size, ideally
=> Create naked container from scratch to make smaller

CREDITS.md, README.md
This pr adds information about running Docker-OSX in Windows, and how to use WSLg's built in X11 server.
=> Readme - Update information regarding using Windows

Dockerfile.naked
Major size changes were made in https://github.com/sickcodes/Docker-OSX/pull/393
And using FROM sickcodes/docker-osx:latest is easier to maintain.
=> Rollback naked

vnc-version/Dockerfile, vnc-version/Dockerfile.nakedvnc
vnc version support arg BASE_IMAGE
=> fix:  support dynamic change of Base image

helm/README.md
=> chore(docs): update helm requirements list style

vnc-version/Dockerfile.nakedvnc
TEMP-FIX is breaking Dockerfile.nakedvnc build #470
=> Fixes #470  TEMP-FIX is breaking Dockerfile.nakedvnc build #470 

README.md
From official MS documentation around `.wslconfig`. Link also has some interesting reading about the `8 second rule` regarding changes not really being made to configs until about 8 seconds after *all* the instance of a distro are shut down. Might be good for some troubleshooting issues with wsl configs not "sticking".
=> Additional information about .wslconfig

README.md
it's should be "experience" not "experiencem"
=> Typing mistake correction

Dockerfile, README.md, tests/boot-images.sh
=> Add latest OS, Ventura

README.md
Found a few minor typos in Readme
=> fixing typos in Readme

README.md
=> Tiny change on Readme: Recommend to Find by name instead of using grep on results

CREDITS.md, FAQ.md
I'm so tired of seeing these questions on Discord.
=> Frequently Asked Questions

README.md
It will be easier to understand which is the most recent version available.
=> README: add version numbers
