- vnc-version/Dockerfile
When you run the VNC version [blob/master/vnc-version/Dockerfile](https://github.com/sickcodes/Docker-OSX/blob/master/vnc-version/Dockerfile) and you stop/restart the container as:
```
docker stop <container ID>
docker start <container ID>
```
Then it fails with:
```
gtk initialization failed
```
This happens when when qemu tries to start. The problem is that the `vncserver` command in `OpenCore-Boot_custom.sh` fails with (but does not terminate the bash script) with the following error:
```
Warning: f21471f8a08f:99 is taken because of /tmp/.X99-lock
Remove this file if there is no X server f21471f8a08f:99
A VNC server is already running as :99
```
Adding `vncserver -kill :99 || true` before `vncserver` fixes the issue.
> Kill badly terminated old vnc session before vnc starts and fix gtk initialization failed

- Dockerfile
Only `BaseSystem.dmg` should be downloaded. But it started to download huge 5GB file while building.
Ref:
https://github.com/corpnewt/gibMacOS/blob/58b48b63dbeeab21994b6cc6a4480ac2bc54b227/gibMacOS.command#L533
> Skip downloading huge files that are not needed

- README.md
`firewalld` doesn't allow DNS requests (this is the case that bit me,
but there might be more) on `docker0` unless the interface is added to
the trusted zone.
See: https://github.com/docker/for-linux/issues/955
Fixes: https://github.com/sickcodes/Docker-OSX/issues/56
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
> Document how to make firewalld work on Fedora with bridged networking

- vnc-version/Dockerfile
Fix gpk error caused by imaging or improper shutdown by removing the `/tmp/.X99-lock` file before starting VNC
> Fix gpk error

- Dockerfile
- README.md
Several proposed improvements:
* remove the need for `privileged`
* reduce final image by ~2.5GB (from 6GB)
* support fallback from kvm to tcg
* use shell expansions and push `DISPLAY` into `ENV` so it does not need to be supplied
* provide example on how to use PulseAudio
* partly resolves https://github.com/sickcodes/Docker-OSX/issues/71
* note that due to (seemingly) the lack of codec driver support there still is no audio support in the guest
> misc improvements to build, runtime and documentation

- Dockerfile
Reduce the `git clone` depth to 1 will make the image size smaller, for more than 100MB!
```
$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docker-osx-new                latest              35f286bfee15        1 minutes ago       3.32GB
docker-osx-old                latest              e476cc91939f        9 minutes ago       3.44GB
```
> Reduce image size by setting git clone depth

- README.md
Hi, I've added some new sections to the docs. Feel free to split this out into a separate README if you think it's getting too long.
- New section on modifications that are useful in a CI/CD environment (or any other environment where you want to run it without graphics). There is also a subsection detailing how to reduce disk usage and compress the qcow2 file.
- New section on enabling USB passthrough. This might make more sense in the future as some kind of modification to the Dockerfile that lets you choose the bus/port numbers via environment variables.
> Docs updates: usb passthrough, headless mode, disk space reduction guide

- helm/README.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
This fixes initial disk creation and adds more installation instructions.
I'm not sure how it worked before on a new install, as it didn't for me when I attempted to rerun it, but here's a version with that fixed and more detailed instructions on it.
Also, I added some more parameters, such as software gpu, system installer version, etc. I am working on getting hardware passthrough gpu support added as well. It may work, but I don't have hardware to test it right now so I left comments saying it's probably broken for the time being.
P.S. Feel free to register at Helm if you haven't already. Thank you!
> Fix helm initial disk creation process and add installation instructions

- helm/Dockerfile
- helm/INSTALL-QEMU-AND-GPU-IOMMU.md
- helm/README.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/templates/service.yaml
- helm/values.yaml
This PR reworks the Dockerfile into a new one just for Kubernetes. Additionally, it switches over to an Ubuntu base because OSX-KVM utilizes Ubuntu for building the OpenCore EFI loader. (I couldn't get it to work with arch) This is required, so Kubernetes can rebuild it adding kexts, changing lower-level settings, and other customizations. Also, helm/kubernetes doesn't need a lot of the configuration in the vanilla Docker version anyway.
Also, this PR introduces GPU passthrough support. This requires extensive configuration on the host--which is documented in another document (I wrote for myself, but and more than willing to share here). That being said, it is catered specifically to my setup--being ClearOS, but it SHOULD work with CentOS pretty easily as well as others. Some of the …
> Add gpu passthrough support as well as dynamic OpenCore chainloader regeneration

- helm/templates/configmap.yaml
- helm/values.yaml
This PR addresses the leftover attribute and command to install a kernel in the pod at runtime. This has been migrated to the Dockerfile itself, so it doesn't take any longer for the pod to start. I accidentally left this in the chart template when I was testing. 😅
Currently, this prevents helm from installing the chart, so this fix is the main reason for this PR.
Additionally, this PR migrates all macOS specific commands out into their own value map so it is a bit cleaner organizationally speaking.
> Fix helm installation failure and cleanup values organization

- README.md
Fixed a small, multi-line shell command in the README
> docs: fix broken multi-line docker command

- Dockerfile
Temporarily downgrade glibc while a new version is being made.
> Tempfix for arch

- CHANGELOG.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
- README.md
- Elevate to version  `3.1`
- Remove `testing` repos as we are not test subjects, currently.
- `archlinux:base-devel` image to skip simple packages.
- Add `glibc` overrides after every `pacman -Syu` which is currently required for non-Arch builds:
```dockerfile
RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst \
&& curl -LO "https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/${patched_glibc}" \
&& bsdtar -C / -xvf "${patched_glibc}" || echo "Everything is fine."
```
> 3.1. archlinux:base-devel. glibc everywhere. Forgo testing repos.

- Dockerfile.auto
Added an unset WGET_OPTIONS so that `hub.docker.com` can download 20GB silently.
General users will see progress, by default.
> Add an unset WGET_OPTIONS variable for hub.docker.com to download 20GB silently, but not general users.

- CHANGELOG.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
- README.md
- custom/config-nopicker-custom.plist
- custom/generate-specific-bootdisk.sh
- custom/generate-unique-machine-values.sh
Example:
```bash
stat mac_hdd_ng.img # make sure you have an image if you're using :naked
touch ./mynewbootdisk.qcow
docker run -it \
--device /dev/kvm \
-e "DISPLAY=${DISPLAY:-:0.0}" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-p 50922:10022 \
-e NOPICKER=true \
-e GENERATE_SPECIFIC=true \
-e DEVICE_MODEL="iMacPro1,1" \
-e SERIAL="C02TW0WAHX87" \
-e BOARD_SERIAL="C027251024NJG36UE" \
-e UUID="5CCB366D-9118-4C61-A00A-E5BAF3BED451" \
-e MAC_ADDRESS="A8:5C:2C:9A:46:2F" \
-e WIDTH=1000 \
-e HEIGHT=1000 \
-e BOOTDISK=/bootdisk \
-v "${PWD}/mynewbootdisk.qcow:/bootdisk" \
-v "${PWD}/mac_hdd_ng.img:/image" \
sickcodes/docker-osx:naked
```
> Add WIDTH and HEIGHT environment variables

- CHANGELOG.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
- custom/generate-unique-machine-values.sh
Change envs to require --envs.
Automatically enable --envs if --output-env is used.
Same for plists, bootdisks^
Fix help ugliness and sanity
> Script for making iMessage serial numbers OpenCore Docker-OSX edits

- Dockerfile
Fixes https://github.com/sickcodes/Docker-OSX/issues/188#issue-831137065
I'm not sure if this is a new bug but it's the first time I've seen it, after reading @C9-Dev's comment:
https://github.com/sickcodes/Docker-OSX/issues/131#issuecomment-798802122
This PR changes default RAM to 2000 which is the minimum.
Perhaps in addition, I could add
```dockerfile
-e RAM=auto \
```
This would only be for blind machines... as most users tend to know how much RAM they have, or their server has already.
```bash
RAM=${RAM:-$(("$(head -n1 /proc/meminfo | tr -dc '[:digit:]') / 900000"))}000 \
exec qemu-system-x86_64 -m ${RAM} \
```
> Propose RAM default to 2G instead of 8G

- CHANGELOG.md
- Dockerfile
- README.md
Fixes https://github.com/sickcodes/Docker-OSX/issues/197
Reverts https://github.com/sickcodes/Docker-OSX/pull/189
```bash
[[ "${RAM}" = max ]] && export RAM="$(("$(head -n1 /proc/meminfo | tr -dc "[:digit:]") / 900000"))"
[[ "${RAM}" = half ]] && export RAM="$(("$(head -n1 /proc/meminfo | tr -dc "[:digit:]") / 2000000"))"
```
E.g. if you have 32GB of ram:
max = 31
half = 16
> Use RAM=max or RAM=half to suit all machines, dynamically.

- CHANGELOG.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
- README.md
…ocation buffer and cache drop bug fix. Add kvm and libvirt groups. Add IMAGE_FORMAT=qcow2 to allow IMAGE_FORMAT=raw too.
Add all ENV variables to each dockerfile for readability.
```
#default
-e IMAGE_FORMAT=qcow2
```
```
-e IMAGE_FORMAT=raw
```
```
#default
-e KVM='accel=kvm:tcg'
```
```
-e KVM=
```
Add note about dropping dedotated wam:
```bash
sudo tee /proc/sys/vm/drop_caches <<< 3
```
> IMAGE_FORMAT=qcow2, KVM= 

- README.md
- Minor corrections.
- Fixed minor punctuation/grammar errors.
- Removed some duplicate instructions.
- Removed/adjusted instructions that were platform-specific.
Additionally, I removed Docker's package installation instructions, as they seemed a bit superfluous and a person with limited Linux skills and no experience with Docker will probably be able to install Docker by themselves. Distros that are generally preferred by beginners, such as Ubuntu, will suggest to the user that they should install Docker, as well as how to install it.
> Made further improvements to the README

- Dockerfile.auto
- Dockerfile.naked
Won't work on :auto because more commands happen
> Remove envsubst to allow interactive QEMU using -i

- README.md
Hi there! I wanted to clean up the base docs a bit based on my experience getting started with Docker-OSX. 
What's changed
- added some links to various closed issues
- fixed dead links
- unified internal link formatting (#the-section-name allows links to work locally and in forks, not just in this repo)
- moved around sections for flow and resized some headings
If this is a lot, feel free to request changes or modify yourself, otherwise I can split this into multiple PRs by commit :slightly_smiling_face:
> README / troubleshooting docs improvements

- CHANGELOG.md
- CREDITS.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
Added to each Dockerfile
```dockerfile
ENV LIBGUESTFS_DEBUG=1
ENV LIBGUESTFS_TRACE=1
```
Added hard exits if generating serials fails to prevent unrelated issues
```bash
|| exit 1 ; } \
```
Silenced arbitrary touch command and start of each `CMD`
> Add LIBGUESTFS debug & trace commands, exit on fail. Update credits

- Dockerfile
Bug for Arch is here: https://bbs.archlinux.org/viewtopic.php?pid=1967285#p1967285
libguestfs mailing list bug is here: https://www.mail-archive.com/libguestfs@redhat.com/msg21721.html
More bug info: https://bugs.astron.com/view.php?id=253
And here: https://bugzilla.redhat.com/show_bug.cgi?id=1945122
Solution here: https://github.com/sickcodes/Docker-OSX/issues/244#issuecomment-821990631
Thank you [@aronzvi](https://github.com/aronzvi) - Fixed Failed to boot OSX with GENERATE_UNIQUE #244
Fixes #244
Fixes  Rare bug: libcrc32c.ko causes libguestfs crash #238
> Downgrade file command for libguestfs

- CHANGELOG.md
- CREDITS.md
- Dockerfile
- Dockerfile.auto
- Dockerfile.naked
Updated PR of https://github.com/sickcodes/Docker-OSX/pull/159
Plus `file` bug. Assuming fixed by now...
> We currently have a dirty fix that looks like this:
> 
> # TEMP-FIX for pacman issue
> RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst \
>     && curl -LO "https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/${patched_glibc}" \
>     && bsdtar -C / -xvf "${patched_glibc}" || echo "Everything is fine."
> # TEMP-FIX for pacman issue
> 
> This PR is just a reminder to repeat build tests until it's fixed upstream as noted:
> 
> #144
> 
> #150
> 
> #152
> Retire glibc patch. Retire file command patch. Add `bootmenu=on`.

- Dockerfile
Have nopicker stock image again. Allows stock NOPICKER=true again.
```dockerfile
ARG STOCK_DEVICE_MODEL=iMacPro1,1
ARG STOCK_SERIAL=C02TM2ZBHX87
ARG STOCK_BOARD_SERIAL=C02717306J9JG361M
ARG STOCK_UUID=007076A6-F2A2-4461-BBE5-BAD019F8025A
ARG STOCK_MAC_ADDRESS=00:0A:27:00:00:00
ARG STOCK_WIDTH=1920
ARG STOCK_HEIGHT=1080
ARG STOCK_MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
ARG STOCK_MASTER_PLIST_URL_NOPICKER=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-nopicker-custom.plist
ARG STOCK_BOOTDISK=/home/arch/OSX-KVM/OpenCore-Catalina/OpenCore.qcow2
ARG STOCK_BOOTDISK_NOPICKER=/home/arch/OSX-KVM/OpenCore-Catalina/OpenCore-nopicker.qcow2
RUN …
```
> Build the missing nopicker stock image at runtime. Add a nopicker stock images in dockerfile.

- CREDITS.md
- README.md
I added option `-e GENERATE_UNIQUE=true` to README.md's example.
> Fix command to launch sickcodes/docker-osx:auto

- README.md
I ran into some issues when running software that was trying to lock files under the nfs folder. This was on Catalina and looks like this is a common issue with Mac -> Linux nfs. 
After digging into it, for my use case using the `locallocks` NFS option on the Mac client resolved it. The `locallocks` option means that locking is handled by the client. There would be problems if you actually need server side locking.
> NFS mount documentation, locking issue

- README.md
Fix typos, more professional language, fix incorrect information.
Using new WSL installation method that uses powershell and not windows features.
Add missing information about .wslconfig.
Re-add info about using WSLg that was removed.
> Update Windows Installation section

- Dockerfile.auto
- Dockerfile.monterey
- Dockerfile.naked
- Dockerfile.naked-auto
Fix the installation of sshpass for the issue #506.
Remove deprecated `MAINTAINER` in favor `LABEL maintainer=`.
> sshpass install and label

- vnc-version/Dockerfile
Without this, `pacman` gives the following errors when trying to update packages as part of the installation:
* The first error is `error: pambase: key "991F6E3F0765CF6295888586139B09DA5BF0D338" is unknown`
* This is followed by a bunch of errors similar to (but with different filenames): `:: File /var/cache/pacman/pkg/pambase-20221020-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)). Do you want to delete it? [Y/n]`
* These are followed by `error: libvpx: key "95220BE99CE6FF778AE0DC670F65C7D881506130" is unknown`
* Finally, it ends with `error: failed to commit transaction (invalid or corrupted package)` and `Errors occurred, no packages were upgraded.` before exiting with code `1`.
This `RUN` command will update the `archlinux-keyring` package to get the …
> Fix issue with invalid GPG keys in VNC version

- Dockerfile
When doing `docker build`, docker (tested with 27.0.3) prints a warning:
LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 238)
This commit fixes it by using proper syntax.
> Fix LegacyKeyValueFormat Docker warning

- Dockerfile
- README.md
Uses same plist as Sonoma. Just needed `-e SHORTNAME=sequoia`. Works already, this PR just adds to the README.md
```bash
docker run -it \
--device /dev/kvm \
-p 50922:10022 \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e "DISPLAY=${DISPLAY:-:0.0}" \
-e GENERATE_UNIQUE=true \
-e CPU='Haswell-noTSX' \
-e CPUID_FLAGS='kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on' \
-e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom-sonoma.plist' \
-e SHORTNAME=sequoia \
sickcodes/docker-osx:latest
```
> Add Sequoia to README.md
